### ISSUE TITLE
Optimize container build process

### ISSUE THREAD

**Issue by SynthLuvr** [MynthAI/base-container-images#3]
**Description**: Currently, the build process for our Docker containers is slow because all containers are built at once, regardless of whether their source code has changed or not. To increase efficiency and decrease the time spent on this process, we should update our build process to only build the containers that have been modified.

**Tasks**:

- [x] Identify a mechanism to track changes in the container's source code or Dockerfile
- [x] Implement this mechanism in the Docker build process to conditionally build containers
- [x] Test the new build process to ensure it works as expected and effectively reduces build time

**Acceptance Criteria**:

- Docker containers should only be built if there have been changes in their Dockerfile or the source code they encompass
- The build process should be noticeably faster than the current process
- All containers still function as expected after a build process
